import os
import uuid
import json
import math
import re
import statistics
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = Path("audit_log.jsonl")
CONTENT_STORE_FILE = Path("content_store.json")


# ---------------------------------------------------------------------------
# Storage helpers
# ---------------------------------------------------------------------------

def load_content_store() -> dict:
    if CONTENT_STORE_FILE.exists():
        with open(CONTENT_STORE_FILE) as f:
            return json.load(f)
    return {}


def save_content_store(store: dict) -> None:
    with open(CONTENT_STORE_FILE, "w") as f:
        json.dump(store, f, indent=2)


def append_log(entry: dict) -> None:
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def get_log(limit: int = 50) -> list:
    if not LOG_FILE.exists():
        return []
    entries = []
    with open(LOG_FILE) as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries[-limit:]


# ---------------------------------------------------------------------------
# Signal 1: LLM-based classification via Groq
# ---------------------------------------------------------------------------

def llm_signal(text: str) -> float:
    """
    Asks llama-3.3-70b-versatile to assess whether the text is AI-generated.
    Returns a float in [0, 1] where 1.0 = definitely AI-generated.

    Captures: semantic coherence, stylistic consistency, overuse of formal
    transitions, balanced sentence construction — holistic writing patterns
    that are hard to capture with statistics alone.

    Blind spot: a skilled human writer who drafts formally (academic papers,
    legal prose) may score high; an AI asked to write sloppily may score low.
    """
    prompt = (
        "You are an expert at identifying whether text was written by a human "
        "or generated by an AI writing tool.\n\n"
        "Analyze the following text and assess how likely it is to be AI-generated.\n\n"
        "Consider:\n"
        "- Vocabulary: AI text tends to use formal, diverse, but suspiciously uniform vocabulary\n"
        "- Sentence structure: AI text tends to produce balanced, complete sentences with low length variance\n"
        "- Natural imperfections: Human writing has typos, casual phrasing, run-ons, genuine personal voice\n"
        "- Filler transitions: AI overuses phrases like 'Furthermore', 'It is important to note', 'In conclusion'\n"
        "- Emotional authenticity: Human writing has irregular emotional texture; AI is consistently composed\n\n"
        "Respond with ONLY valid JSON in this exact format (no markdown, no extra text):\n"
        '{"ai_probability": <float 0.0-1.0>, "reasoning": "<one short sentence>"}\n\n'
        "Text to analyze:\n"
        '"""\n'
        f"{text[:3000]}\n"
        '"""'
    )

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r"\{.*?\}", raw, re.DOTALL)
        if match:
            data = json.loads(match.group())
            prob = float(data.get("ai_probability", 0.5))
            return max(0.0, min(1.0, prob))
    except Exception:
        pass
    return 0.5


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics
# ---------------------------------------------------------------------------

_FILLER_WORDS = {
    "um", "uh", "like", "you know", "kind of", "sort of", "basically",
    "honestly", "literally", "actually", "i mean", "i guess", "you see",
    "anyway", "anyways", "tbh", "ngl", "lol", "haha", "omg", "gonna",
    "wanna", "gotta", "kinda", "sorta", "lemme", "dunno",
}

_AI_PHRASES = [
    "furthermore", "moreover", "additionally", "it is important to note",
    "it is worth noting", "in conclusion", "to summarize", "in summary",
    "it should be noted", "it is essential", "it is crucial", "it is vital",
    "it is imperative", "one must consider", "it is clear that",
    "it is evident that", "as previously mentioned", "in today's world",
    "in today's society", "in the modern era", "delve into", "tapestry",
    "nuanced", "multifaceted", "paradigm shift", "stakeholder", "synergy",
    "leverage", "holistic", "utilize", "it goes without saying",
    "needless to say", "it is undeniable",
]


def stylometric_signal(text: str) -> float:
    """
    Returns a float in [0, 1] where 1.0 = strong AI structural indicators.
    Combines four sub-signals:
      1. Sentence length uniformity (low variance → AI)
      2. Filler/hedge word absence (no fillers → AI)
      3. AI transition/buzzword density (high density → AI)
      4. Type-token ratio zone (mid-range TTR → AI)

    Captures: measurable statistical patterns — structural regularity,
    vocabulary diversity, and stylistic markers that differ between human
    and AI writing at the character/word/sentence level.

    Blind spot: academic or technical human writing has low filler words and
    uses formal transitions legitimately; highly polished human prose can
    resemble AI output on these metrics.
    """
    sentences = _split_sentences(text)
    words = text.lower().split()

    if not sentences or not words:
        return 0.5

    text_lower = text.lower()

    # Sub-signal 1: sentence length uniformity (CV = std / mean)
    sent_lengths = [len(s.split()) for s in sentences if s.strip()]
    if len(sent_lengths) >= 2:
        mean_len = statistics.mean(sent_lengths)
        std_len = statistics.stdev(sent_lengths)
        cv = std_len / mean_len if mean_len > 0 else 0
        # Human CV is typically 0.5–1.2; AI CV tends to be 0.15–0.5
        uniformity_score = max(0.0, min(1.0, 1.0 - (cv / 0.75)))
    else:
        uniformity_score = 0.5

    # Sub-signal 2: filler word absence → more AI
    filler_hits = sum(1 for fw in _FILLER_WORDS if fw in text_lower)
    filler_density = filler_hits / max(len(words) / 20, 1)
    filler_score = max(0.0, min(1.0, 1.0 - min(filler_density, 1.0)))

    # Sub-signal 3: AI transition / buzzword density
    ai_hits = sum(1 for phrase in _AI_PHRASES if phrase in text_lower)
    ai_density = ai_hits / max(len(sentences), 1)
    transition_score = min(1.0, ai_density * 2.5)

    # Sub-signal 4: type-token ratio (unique words / total words)
    ttr = len(set(words)) / len(words)
    # Very low TTR (<0.4): casual/repetitive human; very high (>0.85): creative/academic human
    # Mid-range 0.55–0.78: often AI
    if ttr < 0.40:
        ttr_score = 0.20
    elif ttr > 0.85:
        ttr_score = 0.25
    else:
        ttr_score = 0.40 + 0.55 * math.exp(-((ttr - 0.65) ** 2) / (2 * 0.12 ** 2))
    ttr_score = max(0.0, min(1.0, ttr_score))

    combined = (
        0.30 * uniformity_score
        + 0.25 * filler_score
        + 0.30 * transition_score
        + 0.15 * ttr_score
    )
    return round(max(0.0, min(1.0, combined)), 4)


def _split_sentences(text: str) -> list:
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p.strip()]


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float) -> dict:
    """
    Combines the two signal scores into a final attribution and confidence.

    Weighting: LLM 60% + stylometric 40%.
    The LLM signal receives more weight because it captures semantic and
    holistic stylistic patterns that heuristics cannot.

    Thresholds (on ai_probability):
      >= 0.70  → likely_ai       (confidence = ai_probability)
      <= 0.35  → likely_human    (confidence = 1 - ai_probability)
      else     → uncertain       (confidence reflects distance from 0.525 midpoint)

    A false positive (labeling human work as AI) is treated as the more
    serious error: the "uncertain" band is intentionally wide (0.36–0.69)
    so the system only commits to "likely_ai" when evidence is strong.
    """
    ai_prob = round(0.60 * llm_score + 0.40 * stylo_score, 4)

    if ai_prob >= 0.70:
        attribution = "likely_ai"
        confidence = ai_prob
    elif ai_prob <= 0.35:
        attribution = "likely_human"
        confidence = 1.0 - ai_prob
    else:
        attribution = "uncertain"
        distance_from_center = abs(ai_prob - 0.525)
        confidence = round(distance_from_center / 0.175, 4)

    return {
        "attribution": attribution,
        "ai_probability": ai_prob,
        "confidence": round(min(1.0, confidence), 4),
    }


# ---------------------------------------------------------------------------
# Transparency labels
# ---------------------------------------------------------------------------

def generate_label(attribution: str, confidence: float, ai_probability: float) -> str:
    """
    Maps attribution + confidence onto plain-language text for end users.
    All three variants are meaningfully different — not just swapped numbers.
    """
    pct = int(round(confidence * 100))
    human_pct = int(round((1.0 - ai_probability) * 100))
    ai_pct = int(round(ai_probability * 100))

    if attribution == "likely_ai":
        return (
            f"AI-Generated Content ({pct}% confidence): Our system's analysis strongly suggests "
            f"this content was produced by an AI writing tool. Multiple signals — including writing "
            f"style, sentence structure, and vocabulary patterns — indicate AI authorship. "
            f"If you are the creator and believe this is a mistake, you can submit an appeal."
        )
    elif attribution == "likely_human":
        return (
            f"Human-Written Content ({pct}% confidence): Our system's analysis suggests this content "
            f"was written by a person. The writing shows natural variation, personal voice, and "
            f"characteristics consistent with human authorship. "
            f"If you believe this classification is incorrect, you can submit an appeal."
        )
    else:
        return (
            f"Origin Unclear: Our system could not confidently determine whether this content was "
            f"written by a human or generated by AI. The writing contains a mix of characteristics "
            f"from both ({ai_pct}% AI indicators, {human_pct}% human indicators). "
            f"This content has not been marked either way — the creator may submit an appeal to "
            f"provide additional context for reviewers."
        )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True, silent=True) or {}
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "anonymous").strip()

    if not text:
        return jsonify({"error": "text field is required"}), 400
    if len(text) < 20:
        return jsonify({"error": "text must be at least 20 characters"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    scoring = compute_confidence(llm_score, stylo_score)
    label = generate_label(
        scoring["attribution"],
        scoring["confidence"],
        scoring["ai_probability"],
    )

    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "event": "classification",
        "attribution": scoring["attribution"],
        "ai_probability": scoring["ai_probability"],
        "confidence": scoring["confidence"],
        "llm_score": round(llm_score, 4),
        "stylometric_score": round(stylo_score, 4),
        "label": label,
        "status": "classified",
        "appeal": None,
    }
    append_log(log_entry)

    store = load_content_store()
    store[content_id] = {
        "creator_id": creator_id,
        "attribution": scoring["attribution"],
        "status": "classified",
        "timestamp": timestamp,
    }
    save_content_store(store)

    return jsonify({
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "ai_probability": scoring["ai_probability"],
        "confidence": scoring["confidence"],
        "llm_score": round(llm_score, 4),
        "stylometric_score": round(stylo_score, 4),
        "label": label,
        "status": "classified",
        "timestamp": timestamp,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True, silent=True) or {}
    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    store = load_content_store()
    if content_id not in store:
        return jsonify({"error": "content_id not found"}), 404
    if store[content_id]["status"] == "under_review":
        return jsonify({"error": "an appeal for this content is already under review"}), 409

    timestamp = datetime.now(timezone.utc).isoformat()
    store[content_id]["status"] = "under_review"
    save_content_store(store)

    appeal_entry = {
        "content_id": content_id,
        "event": "appeal_submitted",
        "timestamp": timestamp,
        "creator_id": store[content_id]["creator_id"],
        "original_attribution": store[content_id]["attribution"],
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
    }
    append_log(appeal_entry)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": (
            "Your appeal has been received and logged. "
            "A human reviewer will assess your submission."
        ),
        "timestamp": timestamp,
    })


@app.route("/log", methods=["GET"])
def audit_log():
    limit = request.args.get("limit", 50, type=int)
    entries = get_log(limit=limit)
    return jsonify({"entries": entries, "count": len(entries)})


@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error": "Rate limit exceeded",
        "message": "Too many submissions. Limit: 10 per minute, 100 per day. Please wait before submitting again.",
        "retry_after": str(e.description),
    }), 429


if __name__ == "__main__":
    app.run(debug=True, port=5001)
